//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public UserRole()
        {
            this.Users = new HashSet<User>();
        }
    
        public byte ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool CanEditItem { get; set; }
        public bool CanEditItemCategory { get; set; }
        public bool CanEditPaymentMethod { get; set; }
        public bool CanIssueOrder { get; set; }
        public bool CanApproveOrder { get; set; }
        public bool CanManageUser { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
